### ISSUE TITLE
Crash Report (custom modpack, this is the only mod added between the last time it worked and the first time it didn't)

### ISSUE THREAD

**Issue by enderlord99** [Yopu/NetherBlocker#1]
---- Minecraft Crash Report ----
// Why is it breaking :(

Time: 9/29/15 6:04 PM
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: codechicken/nei/NEIServerConfig
    at codechicken.nei.ServerHandler.loadEvent(ServerHandler.java:45)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_218_ServerHandler_loadEvent_Load.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
    at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:73)
    at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:92)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 8.1 (amd64) version 6.3
    Java Version: 1.8.0_40, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 449629280 bytes (428 MB) / 826277888 bytes (788 MB) up to 954728448 bytes (910 MB)
    JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx1024m
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 16, allocated: 29, tallocated: 77
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1492 34 mods loaded, 34 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAA mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAA FML{7.10.99.99} [Forge Mod Loader](forge-1.7.10-10.13.4.1492-1.7.10-universal.jar) 
    UCHIJAA Forge{10.13.4.1492} [Minecraft Forge](forge-1.7.10-10.13.4.1492-1.7.10-universal.jar) 
    UCHIJAA CodeChickenCore{1.0.4.29} [CodeChicken Core](minecraft.jar) 
    UCHIJAA NotEnoughItems{1.0.3.74} [Not Enough Items](NotEnoughItems-1.7.10-1.0.3.74-universal.jar) 
    UCHIJAA <CoFH ASM>{000} [CoFH ASM](minecraft.jar) 
    UCHIJAA bspkrsCore{6.16} [bspkrsCore]([1.7.10]bspkrsCore-universal-6.16.jar) 
    UCHIJAA FloatingRuins{1.7.10.r02} [FloatingRuins]([1.7.10]FloatingRuins-universal-1.7.10.r02.jar) 
    UCHIJAA StartingInventory{1.7.10.r03} [StartingInventory]([1.7.10]StartingInventory-universal-1.7.10.r03.jar) 
    UCHIJAA Apocalypse{0.0.6} [§cApocalypse§r](Apocalypse-1.7.10-0.0.6.jar) 
    UCHIJAA BattleTowers{1.5.1} [Battle Towers](BattleTowers-1.7.10.jar) 
    UCHIJAA CoFHCore{1.7.10R3.0.3} [CoFH Core](CoFHCore-[1.7.10]3.0.3-303.jar) 
    UCHIJAA CustomSpawner{3.3.0} [DrZhark's CustomSpawner](CustomMobSpawner 3.3.0.jar.zip) 
    UCHIJAA DeadlyWorld{1.0.2} [Deadly World](DeadlyWorld-1.7.10-1.0.2.jar) 
    UCHIJAA dldungeonsjdg{1.8.5} [Doomlike Dungeons](DoomlikeDungeons-1.8.5-MC1.7.10.jar) 
    UCHIJAA MoCreatures{6.3.1} [DrZhark's Mo'Creatures Mod](DrZharks MoCreatures Mod v6.3.1.zip) 
    UCHIJAA EnderIO{1.7.10-2.2.8.381} [Ender IO](EnderIO-1.7.10-2.2.8.381.jar) 
    UCHIJAA EnderStorage{1.4.5.27} [EnderStorage](EnderStorage-1.7.10-1.4.5.27-universal.jar) 
    UCHIJAA EnderZoo{1.7.10-1.0.15.32} [Ender Zoo](EnderZoo-1.7.10-1.0.15.32.jar) 
    UCHIJAA Baubles{1.0.1.10} [Baubles](Baubles-1.7.10-1.0.1.10.jar) 
    UCHIJAA ExtraUtilities{1.2.11} [Extra Utilities](extrautilities-1.2.11.jar) 
    UCHIJAA journeymap{@JMVERSION@} [JourneyMap](journeymap-1.7.10-5.1.0-unlimited.jar) 
    UCHIJAA Mantle{1.7.10-0.3.2.jenkins184} [Mantle](Mantle-1.7.10-0.3.2.jar) 
    UCHIJAA MineTweaker3{3.0.10} [MineTweaker 3](MineTweaker3-1.7.10-3.0.10.jar) 
    UCHIJAA Natura{2.2.0} [Natura](natura-1.7.10-2.2.0.1.jar) 
    UCHIJAA netherblocker{1.7.10-1.0} [Nether Blocker](netherblocker-1.7.10-1.0.jar) 
    UCHIJAA onechunkchallenge{${version}} [One Chunk Challenge](onechunkchallenge-1.7.10-0.2.jar) 
    UCHIJAA Roguelike{1.3.4} [Roguelike Dungeons](roguelike-1.7.10-1.3.4.jar) 
    UCHIJAA AS_Ruins{14.7} [Ruins Spawning System](Ruins-1.7.10.jar) 
    UCHIJAA TConstruct{1.7.10-1.8.7.build979} [Tinkers' Construct](TConstruct-1.7.10-1.8.7.jar) 
    UCHIJAA Thaumcraft{4.2.3.5} [Thaumcraft](Thaumcraft-1.7.10-4.2.3.5.jar) 
    UCHIJAA ThaumicHorizons{1.1.5} [Thaumic Horizons](thaumichorizons-1.7.10-1.1.6.jar) 
    UCHIJAA voiddecay{1.0.10} [VoidDecay](VoidDecay-1.0.10.jar) 
    UCHIJAA aobd{2.8.4} [Another One Bites The Dust](AOBD-2.8.4.jar) 
    GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
    CoFHCore: -[1.7.10]3.0.3-303
    Mantle Environment: Environment healthy.
    TConstruct Environment: Environment healthy.
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Player Count: 0 / 8; []
    Type: Integrated Server (map_client.txt)
    Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by Yopu** [comment]
After searching around still couldn't find the direct cause. Try updating NEI to the latest builds and see if it solves it.
